# Generated by Django 3.2 on 2021-05-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='web_member',
        ),
    ]
